# Generated by Django 5.0.4 on 2024-05-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
