# Generated by Django 5.0.4 on 2024-05-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_paypal_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tansaction_id',
            new_name='transaction_id',
        ),
    ]
