# Generated by Django 5.0.4 on 2024-05-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_tansaction_id_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Recieved', 'Recieved'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], default='Recieved', max_length=15),
        ),
    ]
